### ISSUE TITLE
amadeus services

### ISSUE THREAD

**Issue by LeoTravel** [unseen1980/awesome-travel#35]
hi,

first of all thanks for the repo, great collection of providers!

FYI Amadeus WebServices can be used also for hotels, trains and car rent!

best regards

**Comment by unseen1980** [comment]
Hi @LeoTravel , thanks for letting me know 👍 If you want,  create a PR and I'll be happy to merge. Regards

**Comment by unseen1980** [comment]
Closing this one. Thanks for the info.
